apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: objectbucketclaims.objectbucket.io
spec:
  group: objectbucket.io
  names:
    kind: ObjectBucketClaim
    listKind: ObjectBucketClaimList
    plural: objectbucketclaims
    singular: objectbucketclaim
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                additionalConfig:
                  type: object
                  properties:
                    maxObjects:
                      type: string
                      pattern: '^\d+$'
                    maxSize:
                      type: string
                      pattern: '^\d+$'
          required:
            - spec
      subresources:
        status: {}
  conversion:
    strategy: None
